### ISSUE TITLE
NPM run Dev issue

### ISSUE THREAD

**Issue by Nizey** [nekomy/nekomy-platform#43]
npm run dev

> nekomy@0.1.10 dev /Users/eden/Projects/beta
> webpack-dev-server --config ./webpack/webpack-dev.config.js --watch --colors

Project is running at http://localhost:8080/
webpack output is served from /
Content not from webpack is served from /Users/eden/Projects/beta
404s will fallback to /index.html
fs.js:129
  throw new ERR_INVALID_CALLBACK();
  ^

TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at maybeCallback (fs.js:129:9)
    at Object.writeFile (fs.js:1137:14)
    at VersionFile.writeFile (/Users/eden/Projects/beta/node_modules/webpack-version-file-plugin/index.js:54:8)
    at /Users/eden/Projects/beta/node_modules/webpack-version-file-plugin/index.js:42:18
    at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nekomy@0.1.10 dev: `webpack-dev-server --config ./webpack/webpack-dev.config.js --watch --colors`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nekomy@0.1.10 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/eden/.npm/_logs/2018-10-15T23_13_08_760Z-debug.log

**Comment by haxton09** [comment]
@MrDatastorage I've just managed to resolve this by downgrading nodejs to version 7.9. You can do this using nvm! 

https://github.com/coreybutler/nvm-windows

**Comment by favourch** [comment]
Project is running at http://localhost:8080/
webpack output is served from /
Content not from webpack is served from /home/senseifavour/Documents/dev/courses
404s will fallback to /index.html
fs.js:133
  throw new ERR_INVALID_CALLBACK();
  ^

TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at maybeCallback (fs.js:133:9)
    at Object.writeFile (fs.js:1179:14)
    at VersionFile.writeFile (/home/senseifavour/Documents/dev/courses/node_modules/webpack-version-file-plugin/index.js:54:8)
    at /home/senseifavour/Documents/dev/courses/node_modules/webpack-version-file-plugin/index.js:42:18
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:54:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nekomy@0.1.10 dev: `webpack-dev-server --config ./webpack/webpack-dev.config.js --watch --colors`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nekomy@0.1.10 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by Celina-new** [comment]
Project is running at http://localhost:8080/
webpack output is served from /
Content not from webpack is served from /Users/sunil/Desktop/new project/nekomy-platform
404s will fallback to /index.html
fs.js:128
  throw new ERR_INVALID_CALLBACK();
  ^

TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at maybeCallback (fs.js:128:9)
    at Object.writeFile (fs.js:1163:14)
    at VersionFile.writeFile (/Users/sunil/Desktop/new project/nekomy-platform/node_modules/webpack-version-file-plugin/index.js:54:8)
    at /Users/sunil/Desktop/new project/nekomy-platform/node_modules/webpack-version-file-plugin/index.js:42:18
    at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nekomy@0.1.10 dev: `webpack-dev-server --config ./webpack/webpack-dev.config.js --watch --colors`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nekomy@0.1.10 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/sunil/.npm/_logs/2020-06-23T12_04_45_271Z-debug.log
